# Generated by Django 5.0.2 on 2024-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_deadline_alter_todo_finished_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
    ]
